function F = dynamics(t,x)

global mb mF1 mF2 mF3 mH1 mH2 mH3 
global db dF1 dF2 dF3 dH1 dH2 dH3
global kspringF kspringH bspringF bspringH l0F l0H
global g 
global i2 tfinal


i2 = i2 +1; % increase the counter

%-------------------------------------------------------------------------%
% x(1) = xb 
% x(2) = xb' 
% x(3) = yb
% x(4) = yb'
% x(5) = thb
% x(6) = thb'
% x(7) = thFR1
% x(8) = thFR1'
% x(9) = thFR2
% x(10) = thFR2'
% x(11) = lFR
% x(12) = lFR'
% x(13) = thHR1
% x(14) = thHR1'
% x(15) = thHR2
% x(16) = thHR2'
% x(17) = lHR
% x(18) = lHR'
% x(19) = thFL1
% x(20) = thFL1'
% x(21) = thFL2
% x(22) = thFL2'
% x(23) = lFL
% x(24) = lFL'
% x(25) = thHL1
% x(26) = thHL1'
% x(27) = thHL2
% x(28) = thHL2'
% x(29) = lHL
% x(30) = lHL'
%-------------------------------------------------------------------------%

xb = x(1);
xbdot = x(2); 
yb = x(3);
ybdot = x(4);
thb = x(5);
thbdot = x(6);
thFR1 = x(7);
thFR1dot = x(8);
thFR2 = x(9);
thFR2dot = x(10);
lFR = x(11);
lFRdot = x(12);
thHR1 = x(13);
thHR1dot = x(14);
thHR2 = x(15);
thHR2dot = x(16);
lHR = x(17);
lHRdot = x(18);
thFL1 = x(19);
thFL1dot = x(20);
thFL2 = x(21);
thFL2dot = x(22);
lFL = x(23);
lFLdot = x(24);
thHL1 = x(25);
thHL1dot = x(26);
thHL2 = x(27);
thHL2dot = x(28);
lHL = x(29);
lHLdot = x(30);


%-------------------------------------------------------------------------%
% Coordinates and velocities of feet
%-------------------------------------------------------------------------%
xFRf=xb+db.*cos(thb)+2.*dF1.*sin(thFR1)+dF2.*sin(thFR2)+dF3.*sin( ...
  thFR2)+lFR.*sin(thFR2);
yFRf=yb+(-2).*dF1.*cos(thFR1)+(-1).*dF2.*cos(thFR2)+(-1).*dF3.* ...
  cos(thFR2)+(-1).*lFR.*cos(thFR2)+db.*sin(thb);
xFRfdot=xbdot+2.*dF1.*thFR1dot.*cos(thFR1)+dF2.*thFR2dot.*cos(thFR2) ...
  +dF3.*thFR2dot.*cos(thFR2)+lFR.*thFR2dot.*cos(thFR2)+(-1).* ...
  db.*thbdot.*sin(thb)+lFRdot.*sin(thFR2);
yFRfdot=ybdot+db.*thbdot.*cos(thb)+(-1).*lFRdot.*cos(thFR2)+2.*dF1.* ...
  thFR1dot.*sin(thFR1)+dF2.*thFR2dot.*sin(thFR2)+dF3.* ...
  thFR2dot.*sin(thFR2)+lFR.*thFR2dot.*sin(thFR2);

xHRf=xb+(-1).*db.*cos(thb)+2.*dH1.*sin(thHR1)+dH2.*sin(thHR2)+ ...
  dH3.*sin(thHR2)+lHR.*sin(thHR2);
yHRf=yb+(-2).*dH1.*cos(thHR1)+(-1).*dH2.*cos(thHR2)+(-1).*dH3.* ...
  cos(thHR2)+(-1).*lHR.*cos(thHR2)+(-1).*db.*sin(thb);
xHRfdot=xbdot+2.*dH1.*thHR1dot.*cos(thHR1)+dH2.*thHR2dot.*cos(thHR2) ...
  +dH3.*thHR2dot.*cos(thHR2)+lHR.*thHR2dot.*cos(thHR2)+db.* ...
  thbdot.*sin(thb)+lHRdot.*sin(thHR2);
yHRfdot=ybdot+(-1).*db.*thbdot.*cos(thb)+(-1).*lHRdot.*cos(thHR2)+ ...
  2.*dH1.*thHR1dot.*sin(thHR1)+dH2.*thHR2dot.*sin(thHR2)+dH3.* ...
  thHR2dot.*sin(thHR2)+lHR.*thHR2dot.*sin(thHR2);

xFLf=xb+db.*cos(thb)+2.*dF1.*sin(thFL1)+dF2.*sin(thFL2)+dF3.*sin( ...
  thFL2)+lFL.*sin(thFL2);
yFLf=yb+(-2).*dF1.*cos(thFL1)+(-1).*dF2.*cos(thFL2)+(-1).*dF3.* ...
  cos(thFL2)+(-1).*lFL.*cos(thFL2)+db.*sin(thb);
xFLfdot=xbdot+2.*dF1.*thFL1dot.*cos(thFL1)+dF2.*thFL2dot.*cos(thFL2) ...
  +dF3.*thFL2dot.*cos(thFL2)+lFL.*thFL2dot.*cos(thFL2)+(-1).* ...
  db.*thbdot.*sin(thb)+lFLdot.*sin(thFL2);
yFLfdot=ybdot+db.*thbdot.*cos(thb)+(-1).*lFLdot.*cos(thFL2)+2.*dF1.* ...
  thFL1dot.*sin(thFL1)+dF2.*thFL2dot.*sin(thFL2)+dF3.* ...
  thFL2dot.*sin(thFL2)+lFL.*thFL2dot.*sin(thFL2);

xHLf=xb+(-1).*db.*cos(thb)+2.*dH1.*sin(thHL1)+dH2.*sin(thHL2)+ ...
  dH3.*sin(thHL2)+lHL.*sin(thHL2);
yHLf=yb+(-2).*dH1.*cos(thHL1)+(-1).*dH2.*cos(thHL2)+(-1).*dH3.* ...
  cos(thHL2)+(-1).*lHL.*cos(thHL2)+(-1).*db.*sin(thb);
xHLfdot=xbdot+2.*dH1.*thHL1dot.*cos(thHL1)+dH2.*thHL2dot.*cos(thHL2) ...
  +dH3.*thHL2dot.*cos(thHL2)+lHL.*thHL2dot.*cos(thHL2)+db.* ...
  thbdot.*sin(thb)+lHLdot.*sin(thHL2);
yHLfdot=ybdot+(-1).*db.*thbdot.*cos(thb)+(-1).*lHLdot.*cos(thHL2)+ ...
  2.*dH1.*thHL1dot.*sin(thHL1)+dH2.*thHL2dot.*sin(thHL2)+dH3.* ...
  thHL2dot.*sin(thHL2)+lHL.*thHL2dot.*sin(thHL2);


%-------------------------------------------------------------------------%
% Call the controller
%-------------------------------------------------------------------------%
[tauFR1, tauFR2, tauHR1, tauHR2, tauFL1, tauFL2, tauHL1,...
    tauHL2, xdesFR, ydesFR, xdesFL, ydesFL, xdesHR, ydesHR, xdesHL,... 
    ydesHL] = controller_high_level(t, xb, xbdot, yb, ybdot, thb,...
    thbdot, thFR1, thFR1dot, thFR2, thFR2dot, thHR1, thHR1dot, thHR2,...
    thHR2dot, thFL1, thFL1dot, thFL2, thFL2dot, thHL1,...
    thHL1dot, thHL2, thHL2dot);


%-------------------------------------------------------------------------%
% Ground Forces
%-------------------------------------------------------------------------%
[NFR, FFR, NHR, FHR, NFL, FFL, NHL, FHL, slipFR, slipHR, slipFL, slipHL]...
    = ground_forces(yFRf, yHRf, yFLf, yHLf, xFRfdot, yFRfdot, xHRfdot,...
    yHRfdot, xFLfdot, yFLfdot, xHLfdot, yHLfdot);


%-------------------------------------------------------------------------%
% F matrix
%-------------------------------------------------------------------------%
F = zeros(30,1);


%-------------------------------------------------------------------------%
% from Mathematica we get
%-------------------------------------------------------------------------%
F(2)=FFL+FFR+FHL+FHR+2.*db.*(mF1+mF2+mF3+(-1).*mH1+(-1).*mH2+(-1) ...
  .*mH3).*thbdot.^2.*cos(thb)+(-2).*lFLdot.*mF3.*thFL2dot.* ...
  cos(thFL2)+(-2).*lFRdot.*mF3.*thFR2dot.*cos(thFR2)+(-2).* ...
  lHLdot.*mH3.*thHL2dot.*cos(thHL2)+(-2).*lHRdot.*mH3.* ...
  thHR2dot.*cos(thHR2)+dF1.*(mF1+2.*(mF2+mF3)).*thFL1dot.^2.* ...
  sin(thFL1)+dF2.*mF2.*thFL2dot.^2.*sin(thFL2)+dF2.*mF3.* ...
  thFL2dot.^2.*sin(thFL2)+lFL.*mF3.*thFL2dot.^2.*sin(thFL2)+ ...
  dF1.*mF1.*thFR1dot.^2.*sin(thFR1)+2.*dF1.*mF2.*thFR1dot.^2.* ...
  sin(thFR1)+2.*dF1.*mF3.*thFR1dot.^2.*sin(thFR1)+(lFR.*mF3+ ...
  dF2.*(mF2+mF3)).*thFR2dot.^2.*sin(thFR2)+dH1.*(mH1+2.*(mH2+ ...
  mH3)).*thHL1dot.^2.*sin(thHL1)+dH2.*mH2.*thHL2dot.^2.*sin( ...
  thHL2)+dH2.*mH3.*thHL2dot.^2.*sin(thHL2)+lHL.*mH3.* ...
  thHL2dot.^2.*sin(thHL2)+dH1.*mH1.*thHR1dot.^2.*sin(thHR1)+ ...
  2.*dH1.*mH2.*thHR1dot.^2.*sin(thHR1)+2.*dH1.*mH3.* ...
  thHR1dot.^2.*sin(thHR1)+(lHR.*mH3+dH2.*(mH2+mH3)).* ...
  thHR2dot.^2.*sin(thHR2);

F(4)=(-1).*g.*(mb+2.*(mF1+mF2+mF3+mH1+mH2+mH3))+NFL+NFR+NHL+NHR+( ...
  -1).*dF1.*(mF1+2.*(mF2+mF3)).*thFL1dot.^2.*cos(thFL1)+(-1).* ...
  dF2.*mF2.*thFL2dot.^2.*cos(thFL2)+(-1).*dF2.*mF3.* ...
  thFL2dot.^2.*cos(thFL2)+(-1).*lFL.*mF3.*thFL2dot.^2.*cos( ...
  thFL2)+(-1).*dF1.*mF1.*thFR1dot.^2.*cos(thFR1)+(-2).*dF1.* ...
  mF2.*thFR1dot.^2.*cos(thFR1)+(-2).*dF1.*mF3.*thFR1dot.^2.* ...
  cos(thFR1)+(-1).*(lFR.*mF3+dF2.*(mF2+mF3)).*thFR2dot.^2.* ...
  cos(thFR2)+(-1).*dH1.*(mH1+2.*(mH2+mH3)).*thHL1dot.^2.*cos( ...
  thHL1)+(-1).*dH2.*mH2.*thHL2dot.^2.*cos(thHL2)+(-1).*dH2.* ...
  mH3.*thHL2dot.^2.*cos(thHL2)+(-1).*lHL.*mH3.*thHL2dot.^2.* ...
  cos(thHL2)+(-1).*dH1.*mH1.*thHR1dot.^2.*cos(thHR1)+(-2).* ...
  dH1.*mH2.*thHR1dot.^2.*cos(thHR1)+(-2).*dH1.*mH3.* ...
  thHR1dot.^2.*cos(thHR1)+(-1).*(lHR.*mH3+dH2.*(mH2+mH3)).* ...
  thHR2dot.^2.*cos(thHR2)+2.*db.*(mF1+mF2+mF3+(-1).*mH1+(-1).* ...
  mH2+(-1).*mH3).*thbdot.^2.*sin(thb)+(-2).*lFLdot.*mF3.* ...
  thFL2dot.*sin(thFL2)+(-2).*lFRdot.*mF3.*thFR2dot.*sin(thFR2) ...
  +(-2).*lHLdot.*mH3.*thHL2dot.*sin(thHL2)+(-2).*lHRdot.*mH3.* ...
  thHR2dot.*sin(thHR2);

F(6)=(-1).*tauFL1+(-1).*tauFL2+(-1).*tauFR1+(-1).*tauFR2+(-1).* ...
  tauHL1+(-1).*tauHL2+(-1).*tauHR1+(-1).*tauHR2+db.*(2.*g.*(( ...
  -1).*mF1+(-1).*mF2+(-1).*mF3+mH1+mH2+mH3)+NFL+NFR+(-1).*NHL+ ...
  (-1).*NHR).*cos(thb)+(-1).*db.*dF1.*(mF1+2.*(mF2+mF3)).* ...
  thFL1dot.^2.*cos(thb+(-1).*thFL1)+db.*((-1).*FFL+(-1).*FFR+ ...
  FHL+FHR).*sin(thb)+2.*db.*lFLdot.*mF3.*thFL2dot.*sin(thb+( ...
  -1).*thFL2)+db.*((-1).*(lFL.*mF3+dF2.*(mF2+mF3)).* ...
  thFL2dot.^2.*cos(thb+(-1).*thFL2)+(-1).*dF1.*(mF1+2.*(mF2+ ...
  mF3)).*thFR1dot.^2.*cos(thb+(-1).*thFR1)+dH1.*(mH1+2.*(mH2+ ...
  mH3)).*thHL1dot.^2.*cos(thb+(-1).*thHL1)+dH2.*mH2.* ...
  thHL2dot.^2.*cos(thb+(-1).*thHL2)+dH2.*mH3.*thHL2dot.^2.* ...
  cos(thb+(-1).*thHL2)+lHL.*mH3.*thHL2dot.^2.*cos(thb+(-1).* ...
  thHL2)+dH1.*mH1.*thHR1dot.^2.*cos(thb+(-1).*thHR1)+2.*dH1.* ...
  mH2.*thHR1dot.^2.*cos(thb+(-1).*thHR1)+2.*dH1.*mH3.* ...
  thHR1dot.^2.*cos(thb+(-1).*thHR1)+(lHR.*mH3+dH2.*(mH2+mH3)) ...
  .*thHR2dot.^2.*cos(thb+(-1).*thHR2)+thFR2dot.*((-1).*(lFR.* ...
  mF3+dF2.*(mF2+mF3)).*thFR2dot.*cos(thb+(-1).*thFR2)+2.* ...
  lFRdot.*mF3.*sin(thb+(-1).*thFR2))+(-2).*lHLdot.*mH3.* ...
  thHL2dot.*sin(thb+(-1).*thHL2)+(-2).*lHRdot.*mH3.*thHR2dot.* ...
  sin(thb+(-1).*thHR2));

F(8)=tauFR1+db.*dF1.*(mF1+2.*(mF2+mF3)).*thbdot.^2.*cos(thb+(-1) ...
  .*thFR1)+2.*dF1.*FFR.*cos(thFR1)+(-4).*dF1.*lFRdot.*mF3.* ...
  thFR2dot.*cos(thFR1+(-1).*thFR2)+(-1).*dF1.*(g.*(mF1+2.*( ...
  mF2+mF3))+(-2).*NFR).*sin(thFR1)+(-2).*dF1.*(lFR.*mF3+dF2.*( ...
  mF2+mF3)).*thFR2dot.^2.*sin(thFR1+(-1).*thFR2);

F(10)=tauFR2+(-2).*dF2.*lFRdot.*mF3.*thFR2dot+(dF2+dF3).*FFR.*cos( ...
  thFR2)+dF2.*(mF2+mF3).*(db.*thbdot.^2.*cos(thb+(-1).*thFR2)+ ...
  2.*dF1.*thFR1dot.^2.*sin(thFR1+(-1).*thFR2))+((-1).*dF2.*g.* ...
  (mF2+mF3)+(dF2+dF3).*NFR).*sin(thFR2)+lFR.*(FFR.*cos(thFR2)+ ...
  mF3.*((-2).*lFRdot.*thFR2dot+db.*thbdot.^2.*cos(thb+(-1).* ...
  thFR2)+2.*dF1.*thFR1dot.^2.*sin(thFR1+(-1).*thFR2))+((-1).* ...
  g.*mF3+NFR).*sin(thFR2));

F(12)=kspringF.*l0F+(-1).*kspringF.*lFR+(-1).*bspringF.*lFRdot+( ...
  dF2+lFR).*mF3.*thFR2dot.^2+2.*dF1.*mF3.*thFR1dot.^2.*cos( ...
  thFR1+(-1).*thFR2)+g.*mF3.*cos(thFR2)+(-1).*NFR.*cos(thFR2)+ ...
  (-1).*db.*mF3.*thbdot.^2.*sin(thb+(-1).*thFR2)+FFR.*sin( ...
  thFR2);

F(14)=tauHR1+(-1).*db.*dH1.*(mH1+2.*(mH2+mH3)).*thbdot.^2.*cos( ...
  thb+(-1).*thHR1)+2.*dH1.*FHR.*cos(thHR1)+(-4).*dH1.*lHRdot.* ...
  mH3.*thHR2dot.*cos(thHR1+(-1).*thHR2)+(-1).*dH1.*(g.*(mH1+ ...
  2.*(mH2+mH3))+(-2).*NHR).*sin(thHR1)+(-2).*dH1.*(lHR.*mH3+ ...
  dH2.*(mH2+mH3)).*thHR2dot.^2.*sin(thHR1+(-1).*thHR2);

F(16)=tauHR2+(-2).*dH2.*lHRdot.*mH3.*thHR2dot+(dH2+dH3).*FHR.*cos( ...
  thHR2)+(-1).*dH2.*(mH2+mH3).*(db.*thbdot.^2.*cos(thb+(-1).* ...
  thHR2)+(-2).*dH1.*thHR1dot.^2.*sin(thHR1+(-1).*thHR2))+((-1) ...
  .*dH2.*g.*(mH2+mH3)+(dH2+dH3).*NHR).*sin(thHR2)+lHR.*(FHR.* ...
  cos(thHR2)+(-1).*mH3.*(2.*lHRdot.*thHR2dot+db.*thbdot.^2.* ...
  cos(thb+(-1).*thHR2)+(-2).*dH1.*thHR1dot.^2.*sin(thHR1+(-1) ...
  .*thHR2))+((-1).*g.*mH3+NHR).*sin(thHR2));

F(18)=kspringH.*l0H+(-1).*kspringH.*lHR+(-1).*bspringH.*lHRdot+( ...
  dH2+lHR).*mH3.*thHR2dot.^2+2.*dH1.*mH3.*thHR1dot.^2.*cos( ...
  thHR1+(-1).*thHR2)+g.*mH3.*cos(thHR2)+(-1).*NHR.*cos(thHR2)+ ...
  db.*mH3.*thbdot.^2.*sin(thb+(-1).*thHR2)+FHR.*sin(thHR2);

F(20)=tauFL1+db.*dF1.*(mF1+2.*(mF2+mF3)).*thbdot.^2.*cos(thb+(-1) ...
  .*thFL1)+2.*dF1.*FFL.*cos(thFL1)+(-4).*dF1.*lFLdot.*mF3.* ...
  thFL2dot.*cos(thFL1+(-1).*thFL2)+(-1).*dF1.*(g.*(mF1+2.*( ...
  mF2+mF3))+(-2).*NFL).*sin(thFL1)+(-2).*dF1.*(lFL.*mF3+dF2.*( ...
  mF2+mF3)).*thFL2dot.^2.*sin(thFL1+(-1).*thFL2);

F(22)=tauFL2+(-2).*dF2.*lFLdot.*mF3.*thFL2dot+(dF2+dF3).*FFL.*cos( ...
  thFL2)+dF2.*(mF2+mF3).*(db.*thbdot.^2.*cos(thb+(-1).*thFL2)+ ...
  2.*dF1.*thFL1dot.^2.*sin(thFL1+(-1).*thFL2))+((-1).*dF2.*g.* ...
  (mF2+mF3)+(dF2+dF3).*NFL).*sin(thFL2)+lFL.*(FFL.*cos(thFL2)+ ...
  mF3.*((-2).*lFLdot.*thFL2dot+db.*thbdot.^2.*cos(thb+(-1).* ...
  thFL2)+2.*dF1.*thFL1dot.^2.*sin(thFL1+(-1).*thFL2))+((-1).* ...
  g.*mF3+NFL).*sin(thFL2));

F(24)=kspringF.*l0F+(-1).*kspringF.*lFL+(-1).*bspringF.*lFLdot+( ...
  dF2+lFL).*mF3.*thFL2dot.^2+2.*dF1.*mF3.*thFL1dot.^2.*cos( ...
  thFL1+(-1).*thFL2)+g.*mF3.*cos(thFL2)+(-1).*NFL.*cos(thFL2)+ ...
  (-1).*db.*mF3.*thbdot.^2.*sin(thb+(-1).*thFL2)+FFL.*sin( ...
  thFL2);

F(26)=tauHL1+(-1).*db.*dH1.*(mH1+2.*(mH2+mH3)).*thbdot.^2.*cos( ...
  thb+(-1).*thHL1)+2.*dH1.*FHL.*cos(thHL1)+(-4).*dH1.*lHLdot.* ...
  mH3.*thHL2dot.*cos(thHL1+(-1).*thHL2)+(-1).*dH1.*(g.*(mH1+ ...
  2.*(mH2+mH3))+(-2).*NHL).*sin(thHL1)+(-2).*dH1.*(lHL.*mH3+ ...
  dH2.*(mH2+mH3)).*thHL2dot.^2.*sin(thHL1+(-1).*thHL2);

F(28)=tauHL2+(-2).*dH2.*lHLdot.*mH3.*thHL2dot+(dH2+dH3).*FHL.*cos( ...
  thHL2)+(-1).*dH2.*(mH2+mH3).*(db.*thbdot.^2.*cos(thb+(-1).* ...
  thHL2)+(-2).*dH1.*thHL1dot.^2.*sin(thHL1+(-1).*thHL2))+((-1) ...
  .*dH2.*g.*(mH2+mH3)+(dH2+dH3).*NHL).*sin(thHL2)+lHL.*(FHL.* ...
  cos(thHL2)+(-1).*mH3.*(2.*lHLdot.*thHL2dot+db.*thbdot.^2.* ...
  cos(thb+(-1).*thHL2)+(-2).*dH1.*thHL1dot.^2.*sin(thHL1+(-1) ...
  .*thHL2))+((-1).*g.*mH3+NHL).*sin(thHL2));

F(30)=kspringH.*l0H+(-1).*kspringH.*lHL+(-1).*bspringH.*lHLdot+( ...
  dH2+lHL).*mH3.*thHL2dot.^2+2.*dH1.*mH3.*thHL1dot.^2.*cos( ...
  thHL1+(-1).*thHL2)+g.*mH3.*cos(thHL2)+(-1).*NHL.*cos(thHL2)+ ...
  db.*mH3.*thbdot.^2.*sin(thb+(-1).*thHL2)+FHL.*sin(thHL2);

  
%-------------------------------------------------------------------------%
% We add the odd elements
%-------------------------------------------------------------------------%
F(1) = xbdot;
F(3) = ybdot;
F(5) = thbdot;
F(7) = thFR1dot;
F(9) = thFR2dot;
F(11) = lFRdot;
F(13) = thHR1dot;
F(15) = thHR2dot;
F(17) = lHRdot;
F(19) = thFL1dot;
F(21) = thFL2dot;
F(23) = lFLdot;
F(25) = thHL1dot;
F(27) = thHL2dot;
F(29) = lHLdot;


%-------------------------------------------------------------------------%
% Printing
%-------------------------------------------------------------------------%
if ~mod(i2,200)
    clc
    message2 = ['Running time: ',num2str(t),'s /',num2str(tfinal),'s'];
    disp(message2)
end


